import type {
  AuditLogEntry,
  CaseDetails,
  CaseMessage,
  CaseSummary,
  KnowledgeFile,
  KnowledgeSearchHit,
  MedicalCaseDetails,
  MedicalCaseSummary,
  Patient,
  CatalogEntry,
  ConsultationSuggestion,
  UserSummary,
} from '../types'

export const mockCases: CaseSummary[] = [
  {
    id: 'CASE-24001',
    patientName: '王晨',
    gender: '女',
    age: 32,
    status: 'open',
    chiefComplaint: '反复头痛、乏力 2 周',
    createdAt: '2024-12-28T09:50:00Z',
    updatedAt: '2024-12-28T10:12:00Z',
    doctorName: '李医生',
    tags: ['待追问', '模型补充待确认'],
    unreadMessages: 2,
  },
  {
    id: 'CASE-24002',
    patientName: '赵林',
    gender: '男',
    age: 45,
    status: 'in_review',
    chiefComplaint: '夜间盗汗、易怒',
    createdAt: '2024-12-27T13:40:00Z',
    updatedAt: '2024-12-27T14:00:00Z',
    doctorName: '李医生',
    tags: ['复诊'],
  },
  {
    id: 'CASE-24003',
    patientName: '张敏',
    gender: '女',
    age: 54,
    status: 'closed',
    chiefComplaint: '慢性咳嗽 1 月',
    createdAt: '2024-12-24T08:40:00Z',
    updatedAt: '2024-12-24T09:00:00Z',
    doctorName: '陈医生',
    tags: ['已结案'],
  },
]

export const mockCaseDetails: Record<string, CaseDetails> = {
  'CASE-24001': {
    ...mockCases[0],
    demographics: {
      name: '王晨',
      gender: '女',
      age: 32,
      occupation: '设计师',
      vitals: { bp: '112/74', hr: '78', temp: '36.8' },
    },
    symptoms: ['头痛胀痛', '乏力', '口干', '夜寐不安'],
    notes: '近期工作压力大，饮食不规律，情绪紧张。',
    disease: '偏头痛',
    syndrome: '肝阳上亢',
    formulas: ['天麻钩藤饮'],
    followUps: ['一周内复诊', '记录头痛频次与诱因'],
    auditTags: ['库内推荐', '低置信模型补充'],
  },
  'CASE-24002': {
    ...mockCases[1],
    demographics: {
      name: '赵林',
      gender: '男',
      age: 45,
      occupation: '产品经理',
      vitals: { bp: '126/82', hr: '74', temp: '36.7' },
    },
    symptoms: ['盗汗', '易怒', '口苦'],
    notes: '既往焦虑史，睡眠质量差。',
    disease: '焦虑相关躯体症状',
    syndrome: '心肝火旺',
    formulas: ['龙胆泻肝汤（加减）'],
    followUps: ['两周后复诊', '保持睡眠记录'],
  },
  'CASE-24003': {
    ...mockCases[2],
    demographics: {
      name: '张敏',
      gender: '女',
      age: 54,
      occupation: '教师',
      vitals: { bp: '118/76', hr: '70', temp: '36.6' },
    },
    symptoms: ['干咳少痰', '午后潮热'],
    notes: '已结案，疗效稳定。',
    disease: '慢性咳嗽',
    syndrome: '阴虚火旺',
    formulas: ['沙参麦冬汤'],
    followUps: ['如有复发及时就诊'],
  },
}

export const mockMessages: Record<string, CaseMessage[]> = {
  'CASE-24001': [
    {
      id: 'm1',
      sender: 'patientinfo',
      content: '患者主诉：反复头痛 2 周，伴随乏力、口干。',
      createdAt: '2024-12-28T10:00:00Z',
    },
    {
      id: 'm2',
      sender: 'system',
      content: '根据库内症状匹配，建议追问：头痛是否与情绪相关、是否有失眠。',
      createdAt: '2024-12-28T10:02:00Z',
      citations: [
        {
          fileId: 'kf-001',
          fileName: '头痛辨证要点.pdf',
          fileType: 'pdf',
          page: 12,
          viewUrl: 'https://example.com/knowledge/headache.pdf',
        },
      ],
    },
    {
      id: 'm3',
      sender: 'doctor',
      content: '情绪紧张时加重，最近睡眠浅。',
      createdAt: '2024-12-28T10:04:00Z',
    },
    {
      id: 'm4',
      sender: 'model',
      source: 'model',
      content: '模型补充：可考虑肝阳上亢，建议结合情志调护，方剂：天麻钩藤饮。',
      createdAt: '2024-12-28T10:05:00Z',
      citations: [
        {
          fileId: 'kf-002',
          fileName: '肝阳上亢相关文献.docx',
          fileType: 'docx',
          page: 3,
          viewUrl: 'https://example.com/knowledge/liver-yang.docx',
        },
      ],
    },
  ],
  'CASE-24002': [
    {
      id: 'm5',
      sender: 'patientinfo',
      content: '主诉：夜间盗汗 1 周，易怒，口苦。',
      createdAt: '2024-12-27T14:00:00Z',
    },
    {
      id: 'm6',
      sender: 'system',
      content: '库内匹配：心肝火旺倾向，建议追问入睡耗时、是否胸闷。',
      createdAt: '2024-12-27T14:02:00Z',
    },
  ],
  'CASE-24003': [
    {
      id: 'm7',
      sender: 'system',
      content: '结案：症状稳定，建议保持居家雾化。',
      createdAt: '2024-12-24T09:00:00Z',
    },
  ],
}

export const mockSuggestions: Record<string, ConsultationSuggestion> = {
  'CASE-24001': {
    confidence: 0.73,
    source: 'knowledge-base',
    diseases: ['偏头痛'],
    syndromes: ['肝阳上亢'],
    formulas: ['天麻钩藤饮', '柴胡疏肝散（可选）'],
    followUps: ['记录诱因与频次', '关注睡眠质量'],
    rationale: '症状覆盖率 82%，结合既往病史与年龄匹配。',
  },
  'CASE-24002': {
    confidence: 0.61,
    source: 'model',
    diseases: ['焦虑相关躯体症状'],
    syndromes: ['心肝火旺'],
    formulas: ['龙胆泻肝汤（加减）', '黄连温胆汤（低可信）'],
    followUps: ['建议开展睡眠卫生宣教', '2 周后复诊'],
    rationale: '库内匹配不足，结合向量检索与模型推断。',
  },
}

export const mockUsers: UserSummary[] = [
  {
    id: 'u1',
    name: 'admin',
    username: 'admin',
    realName: '系统管理员',
    role: 'admin',
    status: 'active',
    org: '总部',
    region: '上海',
    phone: '13800001000',
    email: 'admin@example.com',
    note: '拥有全局管理权限。',
    registeredAt: '2024-03-01T00:00:00Z',
    lastLoginAt: '2024-12-28T08:30:00Z',
    registerIp: '10.0.0.2',
    lastLoginIp: '10.0.0.19',
    createdAt: '2024-03-01T00:00:00Z',
    lastActive: '2024-12-28T08:30:00Z',
  },
  {
    id: 'u2',
    name: '李医生',
    username: 'liyisheng',
    realName: '李医生',
    role: 'doctor',
    status: 'active',
    org: '示例医院',
    region: '上海',
    phone: '13800000000',
    email: 'doctor@example.com',
    note: '擅长内科常见病辨证论治。',
    registeredAt: '2024-07-10T00:00:00Z',
    lastLoginAt: '2024-12-28T11:00:00Z',
    registerIp: '10.0.0.8',
    lastLoginIp: '10.0.0.19',
    createdAt: '2024-07-10T00:00:00Z',
    lastActive: '2024-12-28T11:00:00Z',
  },
  {
    id: 'u3',
    name: '陈医生',
    username: 'chenyisheng',
    realName: '陈医生',
    role: 'doctor',
    status: 'suspended',
    org: '示例医院',
    region: '南京',
    phone: '13800000003',
    email: 'chen@example.com',
    note: '账户异常行为已封禁。',
    registeredAt: '2024-08-18T00:00:00Z',
    lastLoginAt: '2024-12-20T10:00:00Z',
    registerIp: '10.0.0.9',
    lastLoginIp: '10.0.0.18',
    createdAt: '2024-08-18T00:00:00Z',
    lastActive: '2024-12-20T10:00:00Z',
  },
]

export const mockCatalog: CatalogEntry[] = [
  {
    id: 'd1',
    name: '偏头痛',
    category: 'disease',
    description: '反复发作的搏动性头痛，伴情绪诱发。',
    linkedTo: ['s1', 'f1'],
  },
  {
    id: 's1',
    name: '肝阳上亢',
    category: 'syndrome',
    description: '头痛眩晕、急躁易怒，舌红少苔。',
    linkedTo: ['f1'],
  },
  {
    id: 'sym1',
    name: '夜间盗汗',
    category: 'symptom',
    description: '夜间入睡后汗出，醒后消失。',
  },
  {
    id: 'f1',
    name: '天麻钩藤饮',
    category: 'formula',
    description: '平肝熄风，适用于肝阳上亢头痛。',
    linkedTo: ['d1', 's1'],
  },
]

export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: 'a1',
    actor: 'admin',
    action: '创建用户 李医生',
    target: 'Users',
    createdAt: '2024-12-18T08:00:00Z',
    severity: 'info',
  },
  {
    id: 'a2',
    actor: '李医生',
    action: '更新病例 CASE-24001 症状列表',
    target: 'Cases',
    createdAt: '2024-12-28T10:12:00Z',
    severity: 'warning',
  },
  {
    id: 'a3',
    actor: '系统',
    action: '模型补充标记：CASE-24002 低置信建议',
    target: 'Consultation',
    createdAt: '2024-12-27T14:05:00Z',
    severity: 'info',
  },
]

export const mockKnowledgeFiles: KnowledgeFile[] = [
  {
    id: 'kf-001',
    fileName: '头痛辨证要点.pdf',
    fileType: 'pdf',
    fileSize: 2_430_000,
    status: 'ready',
    createdAt: '2024-12-10T02:00:00Z',
    updatedAt: '2024-12-10T02:00:00Z',
    viewUrl: 'https://example.com/knowledge/headache.pdf',
  },
  {
    id: 'kf-002',
    fileName: '肝阳上亢相关文献.docx',
    fileType: 'docx',
    fileSize: 680_000,
    status: 'ready',
    createdAt: '2024-12-15T05:00:00Z',
    updatedAt: '2024-12-15T05:00:00Z',
    viewUrl: 'https://example.com/knowledge/liver-yang.docx',
  },
  {
    id: 'kf-003',
    fileName: '方剂学选读.pdf',
    fileType: 'pdf',
    fileSize: 9_020_000,
    status: 'processing',
    createdAt: '2024-12-28T03:10:00Z',
    updatedAt: '2024-12-28T03:10:00Z',
    viewUrl: 'https://example.com/knowledge/formula.pdf',
  },
]

export const mockKnowledgeHits: KnowledgeSearchHit[] = [
  {
    id: 'kh-001',
    fileId: 'kf-001',
    fileName: '头痛辨证要点.pdf',
    fileType: 'pdf',
    page: 12,
    snippet: '……肝阳上亢型头痛，多见头痛胀痛、急躁易怒、睡眠不安……',
    score: 0.82,
    viewUrl: 'https://example.com/knowledge/headache.pdf',
  },
  {
    id: 'kh-002',
    fileId: 'kf-003',
    fileName: '方剂学选读.pdf',
    fileType: 'pdf',
    page: 88,
    snippet: '……天麻钩藤饮，平肝熄风，适用于肝阳上亢之眩晕头痛……',
    score: 0.77,
    viewUrl: 'https://example.com/knowledge/formula.pdf',
  },
  {
    id: 'kh-003',
    fileId: 'kf-002',
    fileName: '肝阳上亢相关文献.docx',
    fileType: 'docx',
    page: 3,
    snippet: '……本研究提示：肝阳上亢与情志因素相关，治疗宜平肝潜阳……',
    score: 0.69,
    viewUrl: 'https://example.com/knowledge/liver-yang.docx',
  },
]

export const mockPatients: Patient[] = [
  {
    id: 'P-001',
    name: '王晨',
    gender: '女',
    age: 32,
    birthday: '1992-05-12',
    region: '上海',
    phone: '13800000001',
    email: 'wangchen@example.com',
    note: '近期工作压力大',
    doctorName: '李医生',
    createdAt: '2024-11-20T02:00:00Z',
    updatedAt: '2024-12-28T10:12:00Z',
  },
  {
    id: 'P-002',
    name: '赵林',
    gender: '男',
    age: 45,
    birthday: '1979-08-03',
    region: '杭州',
    phone: '13800000002',
    email: 'zhaolin@example.com',
    doctorName: '李医生',
    createdAt: '2024-12-01T05:00:00Z',
    updatedAt: '2024-12-27T14:00:00Z',
  },
  {
    id: 'P-003',
    name: '张敏',
    gender: '女',
    age: 54,
    birthday: '1970-02-18',
    region: '南京',
    phone: '13800000003',
    doctorName: '陈医生',
    createdAt: '2024-10-05T01:00:00Z',
    updatedAt: '2024-12-24T09:00:00Z',
  },
]

export const mockMedicalCases: MedicalCaseSummary[] = [
  {
    id: 'MC-10001',
    doctorName: '李医生',
    patientId: 'P-001',
    patientName: '王晨',
    diagnosis: '偏头痛 / 肝阳上亢',
    formulaName: '天麻钩藤饮',
    consultationId: 'CASE-24001',
    createdAt: '2024-12-28T10:20:00Z',
    updatedAt: '2024-12-28T10:20:00Z',
  },
  {
    id: 'MC-10002',
    doctorName: '李医生',
    patientId: 'P-002',
    patientName: '赵林',
    diagnosis: '焦虑相关躯体症状 / 心肝火旺',
    formulaName: '龙胆泻肝汤（加减）',
    consultationId: 'CASE-24002',
    createdAt: '2024-12-27T14:30:00Z',
    updatedAt: '2024-12-28T09:10:00Z',
  },
]

export const mockMedicalCaseDetails: Record<string, MedicalCaseDetails> = {
  'MC-10001': {
    ...mockMedicalCases[0],
    symptoms: '反复头痛、乏力、口干、夜寐不安。',
    formulaDetail: '天麻钩藤饮（纯文本示例）：天麻、钩藤、石决明…（略）',
    usageNote: '每日一剂，水煎分二次温服，连服 7 天。',
  },
  'MC-10002': {
    ...mockMedicalCases[1],
    symptoms: '夜间盗汗、易怒、口苦、睡眠质量差。',
    formulaDetail: '龙胆泻肝汤（加减）（纯文本示例）：龙胆草、黄芩、栀子…（略）',
    usageNote: '每日一剂，水煎分二次温服，连服 14 天。',
  },
}
